version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 654321
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DATABASE_USER: user
      DATABASE_PASSWORD: 654321
      DATABASE_NAME: database
      DATABASE_HOST: mysql  
